### ISSUE TITLE
Correct Training of the Embedding Layer

### ISSUE THREAD

**Issue by BjoernMichele** [pomonam/NetTriangulationEmbedding#1]
Am I right that you train the anchor weights by comparing the result of your embedding Layer with the result of the formula provided for the triangulation embedding function in the paper "Triangulation embedding and democratic aggregation for image search" ? (to get the covariance matrix as well as the subtraction of the Eigenvalues into the anchor weights and find the at the same time the anchor points) Or did I missunderstood your implementation, should there be differences to the result of the formula provided in the paper ?

**Comment by pomonam** [comment]
Hi Hilighter,

Yes, the formula is not identical to the paper. This code only implements up to equation (9) on the paper, where it does not whiten the representation vector. The reason is that the calculation of the covariance vector (inverse) was quite expensive and we were able to get reasonable performance based on the current implementation. It will be straightforward to implement these with the output of the function.

**Comment by BjoernMichele** [comment]
Thank you very much for your answer, it makes of course sense to improve it in this way and then I also understand your Code. Thanks :)
